using System.Linq;
using Microsoft.CodeAnalysis;
using Katera.Generator.Parsing;
using Katera.Generator.Lowering;
using Katera.Generator.Emission;
using Katera.Generator.Utilities;
using Katera.Generator.Validation;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using static Katera.Generator.Emission.Common;

namespace Katera.Generator;

[Generator]
public sealed class KateraGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext ctx)
    {
        var parseResults = ctx.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Katera.BitLayoutAttribute",
                static (node, _) => node is StructDeclarationSyntax,
                static (ctx, _)  => AttributeParser.ParseLayout(ctx));

        var analyzableLayouts = parseResults
            .Where(static r => r.Value is not null)
            .Select(static (r, _) =>
            {
                var model      = r.Value!;
                var validation = LayoutValidator.Validate(model);
                bool hasErrors = !r.Diagnostics.IsEmpty || !validation.IsValid;

                return (Model: model, ParseDiagnostics: r.Diagnostics, Validation: validation, HasErrors: hasErrors);
            });

        var successfulLayouts = analyzableLayouts
            .Where(static pair => !pair.HasErrors)
            .Select(static (pair, _) => pair.Model);

        var invalidLayouts = analyzableLayouts
            .Where(static pair => pair.HasErrors)
            .Select(static (pair, _) => pair.Model);

        var loweredLayouts = successfulLayouts
            .Select(static (model, _) => LayoutLowerer.Lower(model));

        ctx.RegisterSourceOutput(analyzableLayouts, (spc, pair) =>
        {
            foreach (var diag in pair.ParseDiagnostics)
                spc.ReportDiagnostic(CreateDiagnostic(diag));
        });

        ctx.RegisterSourceOutput(analyzableLayouts, (spc, pair) =>
        {
            foreach (var diag in pair.Validation.Diagnostics)
                spc.ReportDiagnostic(CreateDiagnostic(diag));
        });

        ctx.RegisterSourceOutput(loweredLayouts, (spc, plan) =>
        {
            var sb = new SourceBuilder();
            var ns = plan.Namespace;

            sb.Line("// <auto-generated/>");
            sb.Line("using System;");
            sb.Line("using System.Buffers.Binary;");
            sb.Line("using System.Runtime.InteropServices;");
            sb.Line("using System.Runtime.CompilerServices;");
            sb.Line();

            if (!string.IsNullOrEmpty(ns))
                sb.OpenBlock($"namespace {ns}");

            // Owned type
            EmitOwnedHeader(plan, sb);

            switch (plan.OwnedKind)
            {
                case OwnedKind.Register:
                    OwnedRegisterEmitter.EmitOwnedRegisterBody(plan, sb);
                    break;
                case OwnedKind.Blob:
                    BlobEmitter.EmitBlobBody(plan, sb);
                    break;
                case OwnedKind.Expanded:
                    ExpandedEmitter.EmitExpandedBody(plan, sb);
                    break;
            }

            sb.CloseBlock();

            // Overlay type
            sb.Line();
            OverlayEmitter.EmitOverlay(plan, sb);

            if (!string.IsNullOrEmpty(ns))
                sb.CloseBlock();

            spc.AddSource($"{plan.TypeName}.g.cs", sb.ToString());
        });

        ctx.RegisterSourceOutput(invalidLayouts, (spc, model) =>
        {
            var sb = new SourceBuilder();
            InvalidLayoutEmitter.EmitInvalidLayoutBody(model, sb);
            spc.AddSource($"{model.TypeName}.invalid.g.cs", sb.ToString());
        });
    }

    private static Diagnostic CreateDiagnostic(DiagnosticInfo info) =>
        Diagnostic.Create(info.Descriptor, Location.None, info.MessageArgs);
}