using Katera.Generator.Parsing;
using Microsoft.CodeAnalysis;
using Katera.Generator.Utilities;

using static Katera.Generator.Emission.Common;

namespace Katera.Generator.Emission;

internal static class InvalidLayoutEmitter
{
    internal static void EmitInvalidLayoutBody(BitLayoutModel model, SourceBuilder sb)
    {
        sb.Line("// <auto-generated/>");
        sb.Line("using System;");
        sb.Line();

        if (!string.IsNullOrEmpty(model.Namespace))
            sb.OpenBlock($"namespace {model.Namespace}");

        sb.OpenBlock($"{GetAccessibility(model.TypeAccessibility)} partial struct {model.TypeName}");

        foreach (var field in model.BitFieldStubs)
            EmitThrowingProperty(field, sb);

        sb.CloseBlock();

        if (!string.IsNullOrEmpty(model.Namespace))
            sb.CloseBlock();
    }


    private static void EmitThrowingProperty(BitFieldStub field, SourceBuilder sb)
    {
        string staticKeyword = field.IsStatic ? " static" : string.Empty;
        string accessibility = GetAccessibility(field.Accessibility);

        sb.OpenBlock($"{accessibility}{staticKeyword} partial {field.TypeDisplayName} {field.Name}");

        if (field.HasGetter)
            sb.Line($"{GetAccessorPrefix(field.Accessibility, field.GetterAccessibility)}get => throw new global::System.InvalidOperationException(\"Bit layout contains generator diagnostics, property body unavailable.\");");

        if (field.HasSetter)
        {
            string accessor = field.SetterIsInit ? "init" : "set";
            sb.Line($"{GetAccessorPrefix(field.Accessibility, field.SetterAccessibility)}{accessor} => throw new global::System.InvalidOperationException(\"Bit layout contains generator diagnostics, property body unavailable.\");");
        }

        sb.CloseBlock();
        sb.Line();
    }

    private static string GetAccessorPrefix(Accessibility propertyAccessibility, Accessibility accessorAccessibility)
    {
        if (propertyAccessibility == accessorAccessibility)
            return string.Empty;

        return GetAccessibility(accessorAccessibility) + " ";
    }
}