using Microsoft.CodeAnalysis;
using Kata.Generator.Parsing;
using Kata.Generator.Lowering;
using Kata.Generator.Emission;
using Kata.Generator.Utilities;
using Kata.Generator.Validation;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;

using static Kata.Generator.Emission.Common;

namespace Kata.Generator;

[Generator]
public sealed class KataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext ctx)
    {
        var parseResults = ctx.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Kata.BitLayoutAttribute",
                static (node, _) => node is StructDeclarationSyntax,
                static (ctx, _)  => AttributeParser.ParseLayout(ctx));

        var validLayouts = parseResults
            .Where(static r => r.Value is not null)
            .Select(static (r, _) => r.Value!);

        var validatedLayouts = validLayouts
            .Select(static (model, _) => 
            {
                var validation = LayoutValidator.Validate(model);
                return (Model: model, Validation: validation);
            });

        var successfulLayouts = validatedLayouts
            .Where(static pair => pair.Validation.IsValid)
            .Select(static (pair, _) => pair.Model);

        var loweredLayouts = successfulLayouts
            .Select(static (model, _) => LayoutLowerer.Lower(model));

        ctx.RegisterSourceOutput(parseResults, (spc, result) =>
        {
            foreach (var diag in result.Diagnostics)
                spc.ReportDiagnostic(CreateDiagnostic(diag));
        });

        ctx.RegisterSourceOutput(validatedLayouts, (spc, pair) =>
        {
            foreach (var diag in pair.Validation.Diagnostics)
                spc.ReportDiagnostic(CreateDiagnostic(diag));
        });

        ctx.RegisterSourceOutput(loweredLayouts, (spc, plan) =>
        {
            var sb = new SourceBuilder();
            var ns = plan.Namespace;

            sb.Line("// <auto-generated/>");
            sb.Line("using System;");
            sb.Line("using System.Buffers.Binary;");
            sb.Line("using System.Runtime.InteropServices;");
            sb.Line("using System.Runtime.CompilerServices;");
            sb.Line();

            if (!string.IsNullOrEmpty(ns))
                sb.OpenBlock($"namespace {ns}");

            // Owned type
            EmitOwnedHeader(plan, sb);

            switch (plan.OwnedKind)
            {
                case OwnedKind.Register:
                    OwnedRegisterEmitter.EmitOwnedRegisterBody(plan, sb);
                    break;
                case OwnedKind.Blob:
                    break;
                case OwnedKind.Expanded:
                    ExpandedEmitter.EmitExpandedBody(plan, sb);
                    break;
            }

            sb.CloseBlock();

            // Overlay type
            OverlayEmitter.EmitOverlay(plan, sb);

            if (!string.IsNullOrEmpty(ns))
                sb.CloseBlock();

            spc.AddSource($"{plan.TypeName}.g.cs", sb.ToString());
        });
    }

    private static Diagnostic CreateDiagnostic(DiagnosticInfo info) =>
        Diagnostic.Create(info.Descriptor, Location.None, info.MessageArgs);
}