using Microsoft.CodeAnalysis;
using Kata.Generator.Parsing;
using Kata.Generator.Lowering;
using Kata.Generator.Emission;
using Kata.Generator.Utilities;
using Kata.Generator.Validation;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using static Kata.Generator.Emission.Common;

namespace Kata.Generator;

[Generator]
public sealed class KataGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext ctx)
    {
        var layouts = ctx.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Kata.BitLayoutAttribute",
                static (node, _) => node is StructDeclarationSyntax,
                static (ctx, _)  => AttributeParser.ParseLayout(ctx));

        ctx.RegisterSourceOutput(layouts, (spc, result) =>
        {
            if (result.Diagnostic is not null)
            {
                spc.ReportDiagnostic(result.Diagnostic);
                return;
            }

            var layout = result.Model!;
            AttributeParser.ParseFields(layout, spc);
            AttributeParser.ResolveOffsets(layout);
            LayoutValidator.Validate(layout, spc);

            var plan = LayoutLowerer.Lower(layout);
            var sb   = new SourceBuilder();
            var ns   = plan.Symbol.ContainingNamespace.ToDisplayString();

            sb.Line("// <auto-generated/>");
            sb.Line("using System;");
            sb.Line("using System.Buffers.Binary;");
            sb.Line("using System.Runtime.InteropServices;");
            sb.Line("using System.Runtime.CompilerServices;");
            sb.Line();
            if (!string.IsNullOrEmpty(ns))
                sb.OpenBlock($"namespace {ns}");


            // Owned type
            EmitOwnedHeader(plan, sb);

            switch (plan.OwnedKind)
            {
                case OwnedKind.Register:
                    OwnedRegisterEmitter.EmitOwnedRegisterBody(plan, sb);
                    break;
                case OwnedKind.Blob:
                    break;
                case OwnedKind.Expanded:
                    break;
            }

            sb.CloseBlock();


            // Overlay type
            OverlayEmitter.EmitOverlay(plan, sb);


            sb.CloseBlock();
            spc.AddSource($"{plan.Symbol.Name}.g.cs", sb.ToString());
        });
    }
}