<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>

    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>Katera</PackageId>
    <Version>1.0.0</Version>
    <Authors>Pdawg</Authors>
    <Description>A source-generator-based bitfield library for C#</Description>
    <PackageTags>bitfield;source-generator;roslyn</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Katera.Generator\Katera.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" Link="README.md" />
    <None Include="..\LICENSE" Pack="true" PackagePath="\" Link="LICENSE" />
    <None Include="..\Katera.Generator\bin\$(Configuration)\netstandard2.0\Katera.Generator.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
  </ItemGroup>

</Project>
